from typing import Any, Awaitable, Callable, Optional, Protocol


class DMBrowser(Protocol):
    async def open(self) -> "DMBrowser": ...
    async def ensure_logged_in(self, account_id: str) -> None: ...
    async def browse_feed(
        self, duration_seconds: float, like_gate: Optional[Callable[[], Awaitable[bool]]] = None
    ) -> None: ...
    async def send_dm(self, username: str, message: str, pre_send_callback: Any | None = None, on_enter: Any | None = None) -> None: ...
    async def close(self) -> None: ...
