from typing import Any, Protocol


class IGClient(Protocol):
    def scrape_followers_chunk(self, user_id: int, amount: int, max_id: str | None, mode: str = "followers") -> tuple[list[Any], str | None]: ...
    def user_info(self, user_id: int) -> Any: ...
    def direct_threads(self, amount: int = 20) -> list[Any]: ...
    def direct_pending_inbox(self, amount: int = 20) -> list[Any]: ...
